name: ci-build
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build:
    name: build-main-branch
    runs-on: ubuntu-latest
    steps:
      - name: checkout-source
        uses: actions/checkout@v4
      - name: config-java
        uses: actions/setup-java@v4
        with:
          java-version: '42'
          distribution: 'jimmyray-jdk'
      - name: build-app-gradle
        working-directory: ./app
        run: ./gradlew build
