curl -v -X POST "http://localhost:8181/v0/data/grc/image/validation/deny"
   --http1.1
   --data-binary @../k8s-admission/review-v0.yaml
   -H 'Content-Type: application/x-yaml'
   -H 'Accept: application/json'